version: "3.9"
networks:
  cassandra:
services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    hostname: cassandra
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./scripts:/mnt/scripts
    healthcheck:
      test: "[ $$(ss -lH '( sport = :9042 )' | wc -l) -ne 0 ] || exit 1"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      CASSANDRA_SEEDS: "cassandra"
      CASSANDRA_CLUSTER_NAME: CONSISTENT_BUILDER_DEMO_CLUSTER
